apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: nginx
    tier: frontend  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "myhub:5000/nginx:103"
        